package vegetables

var vegetables = [...]string{
	"Amaranth Leaves",
	"Arrowroot",
	"Artichoke",
	"Arugula",
	"Asparagus",
	"Bamboo Shoots",
	"Beans, Green",
	"Beets",
	"Belgian Endive",
	"Bitter Melon",
	"Bok Choy",
	"Broadbeans",
	"Broccoli",
	"Broccoli Rabe",
	"Brussel Sprouts",
	"Cabbage, Green",
	"Cabbage, Red",
	"Carrot",
	"Cassava",
	"Cauliflower",
	"Celeriac ",
	"Celery",
	"Chayote",
	"Chicory",
	"Collards",
	"Corn",
	"Crookneck",
	"Cucumber",
	"Daikon",
	"Dandelion Greens",
	"Edamame, Soybeans",
	"Eggplant",
	"Fennel",
	"Fiddleheads",
	"Ginger Root",
	"Horseradish",
	"Jicama",
	"Kale",
	"Kohlrabi",
	"Leeks",
	"Lettuce, Iceberg",
	"Lettuce, Leaf",
	"Lettuce, Romaine",
	"Mushrooms",
	"Mustard Greens",
	"Okra",
	"Onion",
	"Parsnip",
	"Peas, Green",
	"Pepper, Green",
	"Red pepper",
	"Pepper, Sweet Red",
	"Potato, Red",
	"Potato, White",
	"Potato, Yellow",
	"Pumpkin",
	"Radicchio",
	"Radishes",
	"Rutabaga",
	"Salsify",
	"Shallots",
	"Snow Peas",
	"Sorrel",
	"Spaghetti Squash",
	"Spinach",
	"Squash, Butternut",
	"Sugar Snap Peas",
	"Sweet Potato",
	"Swiss Chard",
	"Tomatillo",
	"Tomato",
	"Turnip",
	"Watercress",
	"Yam Root",
	"Zucchini",
}
