name: Web
on: [push]
defaults:
  run:
    working-directory: web

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x] #node 10.x only

    steps:
    - name: Setup node
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Checkout code with node version ${{ matrix.node-version }}
    - uses: actions/checkout@v1

    - name: Install yarn
    - run: npm install -g yarn

    - name:  Deps
    - run: yarn

    - name: Build
    - run: yarn build

    - name: Test
    - run: yarn test